config/routes.rb
Rails.application.routes.draw do
  resources :demos

end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:name, :description, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing Demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Demos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.name %></td>
        <td><%= demo.description %></td>
        <td><%= demo.number %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New Demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @demo.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @demo.number %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>